### ISSUE TITLE
Crashing on world load after updating to latest dev snapshot

### ISSUE THREAD

**Issue by klaidas01** [Nomifactory/GregTech#12]
**Pack Version:**
dev-579c535

**Description:**
After updating from 1.3-rc-20230128 to the latest dev snapshot (using curse forge launcher) minecraft crashes on world load. Looks like the crash is caused by electric blast furnaces which were running at the time of saving the world, idle blast furnaces load without issue

**Expected Behavior:**
World should load without crashing

**Steps To Reproduce:**
Create a world in 1.3-rc-20230128 and save with blast furnaces running. Move save to dev-579c535 and try loading the world.

**Crash Log:**
[crash-2024-06-09_11.51.28-server.txt](https://github.com/user-attachments/files/15751237/crash-2024-06-09_11.51.28-server.txt)

**Comment by Exaxxion** [comment]
Transferred to GTNE repository. I see the issue in the code. Thank you for reporting the issue.

**Comment by Exaxxion** [comment]
@klaidas01 Please try replacing the 1.18.2 jar with the 1.18.3 jar in your mods folder. If you want it before it's processed and approved on CurseForge, you can get it from the GitHub releases page.

When updating from an older version, the active smelt won't enforce coil-specific jamming constraints as a fallback, as it won't have any recorded. It will enforce them normally for all recipes after that one completes. Most importantly, it will not crash.

**Comment by klaidas01** [comment]
Everything seems to be working with 1.18.2, thanks for the quick fix
